apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-python-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-python-deploy
  template:
    metadata:
      labels:
        app: api-python-deploy
    spec:
      containers:
      - name: api-python-deploy
        image: magnocarlos1988/api-python-uv-project:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DATABASE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: api-python-svc
spec:
  selector:
    app: api-python-deploy
  ports:
  - port: 8000
    targetPort: 8000
